version: '3.8'

services:
  # MongoDB数据库服务
  mongo:
    image: mongo:5.0
    restart: unless-stopped
    container_name: teacher-exam-mongo
    # 限制资源使用
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 256M
    command: --wiredTigerCacheSizeGB 0.25 --oplogSize 128
    volumes:
      - mongo-data:/data/db
      # 添加初始化脚本，创建索引
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_DATABASE: teacher-exam
    networks:
      - app-network

  # 应用程序服务
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: teacher-exam-app
    # 限制资源使用
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 768M
        reservations:
          cpus: '0.3'
          memory: 384M
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGO_URI: mongodb://mongo:27017/teacher-exam
    networks:
      - app-network
    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  # Nginx代理服务
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    container_name: teacher-exam-nginx
    # 限制资源使用
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/usr/share/nginx/html:ro
      - logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - app-network

# 持久化存储卷
volumes:
  mongo-data:
  logs:

# 网络配置
networks:
  app-network:
    driver: bridge
